"""'state' field in locations table

Revision ID: 5c20821103b9
Revises: 9cb4f80fe02d
Create Date: 2026-03-19 09:42:17.138895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c20821103b9'
down_revision: Union[str, Sequence[str], None] = '9cb4f80fe02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('state', sa.String(), nullable=True))
    # Populate existing location entries with 'NJ'
    op.execute("UPDATE locations SET state = 'NJ'")
    # Make column not nullable
    op.alter_column('locations', 'state', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'state')
    # ### end Alembic commands ###
