"""name unique constraint

Revision ID: b8adf56b3f49
Revises: 
Create Date: 2026-03-17 14:10:02.691708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8adf56b3f49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'casinos', ['name'])
    op.create_unique_constraint(None, 'locations', ['name'])
    op.create_unique_constraint(None, 'quants', ['name'])
    op.create_unique_constraint(None, 'testers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testers', type_='unique')
    op.drop_constraint(None, 'quants', type_='unique')
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'casinos', type_='unique')
    # ### end Alembic commands ###
